# Generated by Django 4.1 on 2023-03-23 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('math_subject', models.IntegerField(verbose_name='数学')),
                ('chinese_subject', models.IntegerField(verbose_name='语文')),
                ('English_subject', models.IntegerField(verbose_name='英语')),
                ('ave', models.IntegerField(default=0, verbose_name='平均成绩')),
                ('sum', models.IntegerField(default=0, verbose_name='总成绩')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classinfo', verbose_name='班级')),
            ],
        ),
    ]
