# Generated by Django 4.1 on 2023-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='chinese_subject',
            new_name='chinese_score',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='English_subject',
            new_name='english_score',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='math_subject',
            new_name='math_score',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='ave',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='sum',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ave_score',
            field=models.IntegerField(default=0, editable=False, verbose_name='平均成绩'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='total_score',
            field=models.IntegerField(default=0, editable=False, verbose_name='总成绩'),
        ),
    ]
