# Generated by Django 4.1 on 2023-03-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_chinese_subject_studentinfo_chinese_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='ave_score',
        ),
    ]
